///////////////////////////////////////////////////////////
//  DetalleExposicion.cs
//  Implementation of the Class DetalleExposicion
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2021 18:44:59
//  Original author: u149459
///////////////////////////////////////////////////////////

namespace MuseoPictoricoG11.Modelos
{

    public class DetalleExposicion : Entidad
    {

        private string lugarAsignado;
        public virtual Obra m_Obra { get; set; }
        public virtual string LugarAsignado { get => lugarAsignado; set => lugarAsignado = value; }

        public DetalleExposicion()
        {

        }

        ~DetalleExposicion()
        {

        }

        public virtual int getDuracionResumida()
        {
            return m_Obra.getDuracionResumida();
        }
    }
}//end DetalleExposicion