///////////////////////////////////////////////////////////
//  Entrada.cs
//  Implementation of the Class Entrada
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2021 19:42:18
///////////////////////////////////////////////////////////


using System;

namespace MuseoPictoricoG11.Modelos
{


    public class Entrada : Entidad
    {
        private int idSedeEntradaTarifa;
        private DateTime fechaVenta;
        private TimeSpan horaVenta;
        private double monto;
        private int numero;
        public virtual Tarifa m_Tarifa { get; set; }
        public virtual Sede m_Sede { get; set; }
        public virtual DateTime FechaVenta { get => fechaVenta; set => fechaVenta = value; }
        public virtual TimeSpan HoraVenta { get => horaVenta; set => horaVenta = value; }
        public virtual double Monto { get => monto; set => monto = value; }
        public virtual int Numero { get => numero; set => numero = value; }

        //public AsignacionVisita m_AsignacionVisita;

        public Entrada(Sede sede, Tarifa tarifa, DateTime fechaActual, double monto, int numeroEntrada)
        {
            this.fechaVenta = fechaActual;
            this.horaVenta = new TimeSpan(fechaActual.Hour, fechaActual.Minute, fechaActual.Second);
            this.monto = monto;
            this.numero = numeroEntrada;
            this.m_Sede = sede;
            this.m_Tarifa = tarifa;
        }

        public Entrada() { }
        ~Entrada() { }


        public virtual int getNumero()
        {

            return Numero;
        }

        public virtual void setNumero(int numeroEntrada)
        {
            this.numero = numeroEntrada;
        }

        public virtual void setTarifa(Tarifa tarifa)
        {
            this.m_Tarifa = tarifa;
        }

        public virtual bool sosDeFecha(DateTime fecha)
        {
            DateTime dtFechaVenta = new DateTime(fechaVenta.Year, fechaVenta.Month, fechaVenta.Day);
            DateTime dtFechaActual = new DateTime(fecha.Year, fecha.Month, fecha.Day);
            return (dtFechaVenta == dtFechaActual) ? true : false;
        }

        public virtual bool sosDeSede(Sede sede)
        {
            if (m_Sede.Id == sede.Id) return true;
            return false;
        }

        public virtual void setFechaVenta(DateTime fechaVenta)
        {
            this.fechaVenta = fechaVenta;
        }

        public virtual DateTime getFechaVenta()
        {
            return this.fechaVenta;
        }

        public virtual void setHoraVenta(TimeSpan horaVenta)
        {
            this.horaVenta = horaVenta;
        }

        public virtual TimeSpan setHoraVenta()
        {
            return horaVenta;
        }

        public virtual void setMonto(double monto)
        {
            this.monto = monto;
        }

        public virtual double getMonto()
        {
            return this.monto;
        }

        public virtual void setIdSedeEntradaTarifa(int idSedeEntradaTarifa)
        {
            this.idSedeEntradaTarifa = idSedeEntradaTarifa;
        }

        private void setSede(Sede sede)
        {
            this.m_Sede = sede;
        }

    }
}//end Entrada