///////////////////////////////////////////////////////////
//  Exposicion.cs
//  Implementation of the Class Exposicion
//  Generated by Enterprise Architect
//  Created on:      25-jun.-2021 20:17:27
///////////////////////////////////////////////////////////




using System;
using System.Collections.Generic;

namespace MuseoPictoricoG11.Modelos
{
    public class Exposicion : Entidad
    {

        private DateTime fechaFinReplanificada;
        private DateTime fechaHoraFin;
        private DateTime fechaInicioReplanificada;
        private DateTime horaApertura;
        private DateTime horaCierre;
        private string nombre;
        public virtual IList<DetalleExposicion> m_DetalleExposicion { get; set; } = new List<DetalleExposicion>();

        public virtual DateTime FechaFinReplanificada { get => fechaFinReplanificada; set => fechaFinReplanificada = value; }
        public virtual DateTime FechaHoraFin { get => fechaHoraFin; set => fechaHoraFin = value; }
        public virtual DateTime FechaInicioReplanificada { get => fechaInicioReplanificada; set => fechaInicioReplanificada = value; }
        public virtual DateTime HoraApertura { get => horaApertura; set => horaApertura = value; }
        public virtual DateTime HoraCierre { get => horaCierre; set => horaCierre = value; }
        public virtual string Nombre { get => nombre; set => nombre = value; }

        public Exposicion()
        {

        }

        ~Exposicion()
        {

        }

        public virtual int calcularDuracionResumida()
        {
            int duracionResumida = 0;
            foreach (var detalleExposicion in m_DetalleExposicion)
            {
                duracionResumida += detalleExposicion.getDuracionResumida();
            }
            return duracionResumida;
        }


        public virtual bool esVigente(DateTime fecha)
        {
            return (fechaFinReplanificada == null || fecha < fechaFinReplanificada) && fecha > fechaInicioReplanificada;
        }
    }
}//end Exposicion