///////////////////////////////////////////////////////////
//  Obra.cs
//  Implementation of the Class Obra
//  Generated by Enterprise Architect
//  Created on:      26-jun.-2021 18:57:36
///////////////////////////////////////////////////////////



using System;

namespace MuseoPictoricoG11.Modelos
{

    public class Obra : Entidad
    {

        private double alto;
        private double ancho;
        private int codigoSensor;
        private string descripcion;
        private int duracionExtendida;
        private int duracionResumida;
        private DateTime fechaCreacion;
        private string nombre;
        private double peso;
        private double valuacion;

        public Obra()
        {

        }

        ~Obra()
        {

        }

        public virtual double Alto { get => alto; set => alto = value; }
        public virtual double Ancho { get => ancho; set => ancho = value; }
        public virtual int CodigoSensor { get => codigoSensor; set => codigoSensor = value; }
        public virtual string Descripcion { get => descripcion; set => descripcion = value; }
        public virtual int DuracionExtendida { get => duracionExtendida; set => duracionExtendida = value; }
        public virtual int DuracionResumida { get => duracionResumida; set => duracionResumida = value; }
        public virtual DateTime FechaCreacion { get => fechaCreacion; set => fechaCreacion = value; }
        public virtual string Nombre { get => nombre; set => nombre = value; }
        public virtual double Peso { get => peso; set => peso = value; }
        public virtual double Valuacion { get => valuacion; set => valuacion = value; }

        public virtual int getDuracionResumida()
        {
            return duracionResumida;
        }
    }
}//end Obra