///////////////////////////////////////////////////////////
//  Tarifa.cs
//  Implementation of the Class Tarifa
//  Generated by Enterprise Architect
//  Created on:      25-jun.-2021 20:19:24
///////////////////////////////////////////////////////////



using System;

namespace MuseoPictoricoG11.Modelos
{

    public class Tarifa : Entidad
    {
        private int id;
        private DateTime fechaFinVigencia;
        private DateTime fechaInicioVigencia;
        private double monto;
        private double montoAdicionalGuia;
        public virtual TipoDeEntrada m_TipoDeEntrada { get; set; }
        public virtual TipoVisita m_TipoVisita { get; set; }

        public Tarifa()
        {

        }


        public virtual DateTime FechaFinVigencia { get => fechaFinVigencia; set => fechaFinVigencia = value; }
        public virtual DateTime FechaInicioVigencia { get => fechaInicioVigencia; set => fechaInicioVigencia = value; }
        public virtual double Monto { get => monto; set => monto = value; }
        public virtual double MontoAdicionalGuia { get => montoAdicionalGuia; set => montoAdicionalGuia = value; }

        public virtual bool esVigente(DateTime fecha)
        {
            return (FechaFinVigencia > fecha) ? true : false;
        }

        public virtual int getId()
        {
            return this.Id;
        }
        public virtual double getMonto()
        {
            return Monto;
        }

        public virtual double getMontoAdicionalPorGuia()
        {
            return MontoAdicionalGuia;
        }

        public virtual TipoDeEntrada getTipoDeEntrada()
        {
            return m_TipoDeEntrada;
        }

        public virtual TipoVisita getTipoVisita()
        {
            return m_TipoVisita;
        }
    }
}//end Tarifa